CREATE TABLE "C##OWNER"."CAR_INFO"(
CAR_ID NUMBER(20) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
BRAND VARCHAR2(20 BYTE) NOT NULL,
MODEL VARCHAR2(20 BYTE) NOT NULL,
PRODUCTION_YEAR VARCHAR2(20 BYTE) NOT NULL,
STATUS CLOB,
DESTINATION CLOB,
IS_ACTIVE NUMBER(1,0),
CREATED_BY VARCHAR2(20 BYTE) NOT NULL,
CREATED_DATE TIMESTAMP(6) NOT NULL,
LAST_UPDATED_BY VARCHAR2(20 BYTE) NOT NULL,
LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL
)
GRANT UPDATE ON "C##OWNER"."CAR_INFO" TO "C##OWNER"
GRANT INSERT ON "C##OWNER"."CAR_INFO" TO "C##OWNER"
GRANT SELECT ON "C##OWNER"."CAR_INFO" TO "C##OWNER"
GRANT DELETE ON "C##OWNER"."CAR_INFO" TO "C##OWNER"