CREATE TABLE "C##OWNER"."USERS" (
USER_ID NUMBER(20) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
FIRST_NAME VARCHAR2(20 BYTE) NOT NULL,
LAST_NAME VARCHAR2(20 BYTE) NOT NULL,
DATE_OF_BIRTH DATE NOT NULL,
EMAIL VARCHAR2(20 BYTE) NOT NULL,
PHONE_NUMBER NUMBER(9),
PASSWORD VARCHAR2(20 BYTE) NOT NULL,

IS_ACTIVE NUMBER(1,0),
CREATED_BY VARCHAR2(20 BYTE) NOT NULL,
CREATED_DATE TIMESTAMP(6) NOT NULL,
LAST_UPDATED_BY VARCHAR2(20 BYTE) NOT NULL,
LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL
)

GRANT UPDATE ON "C##OWNER"."USERS" TO "C##OWNER"
GRANT INSERT ON "C##OWNER"."USERS" TO "C##OWNER"
GRANT SELECT ON "C##OWNER"."USERS" TO "C##OWNER"
GRANT DELETE ON "C##OWNER"."USERS" TO "C##OWNER"