CREATE TABLE "C##OWNER"."RESERVATIONS" (
RECORD_ID NUMBER(20) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
CAR_ID NUMBER(20) NOT NULL,
USER_ID NUMBER(20) NOT NULL,
RESERVATION_TIME TIMESTAMP(6) NOT NULL,
COST DOUBLE(8 BYTE) NOT NULL,
DRIVER VARCHAR2(40 BYTE) NOT NULL,

IS_ACTIVE NUMBER(1,0) NOT NULL,
CREATED_BY VARCHAR2(40 BYTE) NOT NULL,
CREATED_DATE TIMESTAMP(6) NOT NULL,
LAST_UPDATED_BY VARCHAR2(40 BYTE) NOT NULL,
LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL
)


GRANT UPDATE ON "C##OWNER"."RESERVATIONS" TO "C##OWNER"
GRANT INSERT ON "C##OWNER"."RESERVATIONS" TO "C##OWNER"
GRANT SELECT ON "C##OWNER"."RESERVATIONS" TO "C##OWNER"
GRANT DELETE ON "C##OWNER"."RESERVATIONS" TO "C##OWNER"